### PR TITLE
Fix Turnstile field display logic in post forms

### LINKED ISSUE #1571: [Bug] Turnstile field not working in post form
Description: The turnstile field is not working in post form. If I turn on Turnstile for the login form, it will work on the post form. But there should be no relation between these two.

Steps:
1. Add turnstiles credentials from settings and turn on (in general options)
2. Create a post form > add turnstile field and save
3. observe that turnstile is not in frontend for that form
4. Go to settings > Login/Registration> turn on turnstile for login
5. Now observe that turnstile is available in the previously created form 

Screen Record:

https://github.com/user-attachments/assets/3e89b2ef-4189-426c-89ad-add8e1a3fdf2

### PR DESCRIPTION
**Pull request by arifulhoque7**
- Change condition from login_form_turnstile to global enable_turnstile setting
- Turnstile field in post forms should be controlled by global setting, not login-specific setting
- Fixes issue where Turnstile field was incorrectly hidden/shown based on login form setting

Fixes: Turnstile field display logic inconsistency

Close #1571 

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved the handling of the Cloudflare Turnstile field to better respect the enablement setting and prevent rendering when not configured or enabled.

### CODE REVIEW

File: includes/Fields/Form_Field_Cloudflare_Turnstile.php [hunk 1]
```diff
@@ -25,13 +25,13 @@ public function __construct() {
...
-        $size      = ! empty( $field_settings['turnstile_size'] ) ? $field_settings['turnstile_size'] : 'normal';
-        $action    = ! empty( $field_settings['turnstile_type'] ) ? $field_settings['turnstile_type'] : 'non-interactive';
+        $enable_turnstile = wpuf_get_option( 'enable_turnstile', 'wpuf_general', 'off' );
+        $site_key         = wpuf_get_option( 'turnstile_site_key', 'wpuf_general', '' );
+        $theme            = ! empty( $field_settings['turnstile_theme'] ) ? $field_settings['turnstile_theme'] : 'light';
+        $size             = ! empty( $field_settings['turnstile_size'] ) ? $field_settings['turnstile_size'] : 'normal';
+        $action           = ! empty( $field_settings['turnstile_type'] ) ? $field_settings['turnstile_type'] : 'non-interactive';
 
-        if ( 'off' === $turnstile || empty( $site_key ) ) {
+        if ( 'on' !== $enable_turnstile || empty( $site_key ) ) {
```
Comment (sapayth) [inline includes/Fields/Form_Field_Cloudflare_Turnstile.php]: use `wpuf_is_checkbox_or_toggle_on( $enable_turnstile )` function for better handling

**Review by sapayth — CHANGES_REQUESTED** [review]
use `wpuf_is_checkbox_or_toggle_on( $enable_turnstile )` function for better handling

**Comment by arifulhoque7** [comment]
> use `wpuf_is_checkbox_or_toggle_on( $enable_turnstile )` function for better handling

done vai
